name: Cloudfront OAC to S3

# Trigger github action manually only
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-east-1"

jobs:
  setup-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Assume OIDC Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.ASSUME_ROLE_ARN}}
          aws-region: us-east-1
      - name: Create S3 bucket for remote backend configuration of Terraform
        run: |
          aws s3 mb s3://${{ github.GITHUB_REPOSITORY }}-terraform-backend --region $AWS_REGION
